---
# tasks file for whc-cell
- name: Print New EC2 Key Pair Private Key
  debug:
    msg: "New EC2 Key Pair for VPC = {{ ec2_private_key.key.name }}"
  when: ec2_private_key.key.private_key is defined

- name: Save Private Key to File
  copy:
    content: "{{ ec2_private_key.key.private_key }}"
    dest: "{{ whc_keydir }}/{{ key_name }}.private_key"
    mode: 0600
  when: ec2_private_key.key.private_key is defined and whc_savekeys == 'yes'
