---
# tasks file for vpc-subnets

- name: Create Private Subnets
  ec2_vpc_subnet:
    state: "{{ state }}"
    vpc_id: "{{ whc_vpc.vpc.id }}"
    region: "{{ whc_region }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    resource_tags:
      Name: "{{ vpc_name }}-{{ item.name }}"
  with_items: "{{ whc_core_subnets }}"
  when: whc_state == "present"
