# vim:ff=unix ts=2 sw=2 ai expandtab

- hosts: localhost
  connection: local
  remote_user: ec2-user
  gather_facts: no




  vars_files:
    - "vars/whc-cell/{{ targetenv }}.yaml"

  pre_tasks:
    - name: Validate environment value was passed
      fail: msg="ERROR --- A valid targetenv value was not passed in extra-vars. Valid values are listed in group_vars/all"
      when: targetenv is not defined or (targetenv is defined and targetenv not in environments)


  roles:
  - name: Create a WHC Cell
    role: whc-cell
    vpc_name: "whc-{{ targetenv }}-{{ whc_region }}"
    vpc_cidrblock: "{{ whc_cidrblock }}"
    vpc_region: "{{ whc_region }}"
    vpc_state: "{{ whc_state }}"
    multi_ok: no
