# vim:ff=unix ts=2 sw=2 ai expandtab

- hosts: localhost
  connection: local
  remote_user: ec2-user
  gather_facts: no

  vars_files:
    - "vars/whc-cell/{{ targetenv }}.yaml"

  vars:
    vpc_name: "whc-{{ targetenv }}-{{ whc_region }}"
    key_name: "whc-{{ targetenv }}-{{ whc_region }}-key"

  pre_tasks:
    - name: Validate environment value was passed
      fail: msg="ERROR --- A valid targetenv value was not passed in extra-vars. Valid values are listed in group_vars/all"
      when: targetenv is not defined or (targetenv is defined and targetenv not in environments)


  roles:
  - name: Create a WHC Cell
    role: whc-cell
    vpc_cidrblock: "{{ whc_cidrblock }}"
    vpc_region: "{{ whc_region }}"
    state: "{{ whc_state }}"
    multi_ok: no

  tasks:
  - name: Print New EC2 Key Pair Private Key
    debug:
      msg: "New EC2 Key Pair for VPC = {{ ec2_private_key.key.name }}"
    when: ec2_private_key.key.private_key is defined

  - name: Save Private Key to File
    copy:
      content: "{{ ec2_private_key.key.private_key }}"
      dest: "{{ whc_keydir }}/{{ key_name }}.private_key"
      mode: 0600
    when: ec2_private_key.key.private_key is defined and whc_savekeys == 'yes'
