---

- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - "vars/whc-cell/{{ targetenv }}.yaml"

  vars:
    vpc_name: "whc-{{ targetenv }}-{{ whc_region }}"
    key_name: "{{ vpc_name }}-key"

  pre_tasks:
    - name: Validate environment value was passed
      fail: msg="ERROR --- A valid targetenv value was not passed in extra-vars. Valid values are listed in group_vars/all"
      when: targetenv is not defined or (targetenv is defined and targetenv not in environments)

  tasks:

    - name: Fetching VPC Facts
      ec2_vpc_net_facts:
        region: "{{ whc_region }}"
        filters:
          "tag:Name": "{{ vpc_name }}"
          cidr: "{{ whc_cidrblock }}"
      ignore_errors: 'yes'
      register: vpc_facts

    - name: Fetching VPC Subnet Facts
      ec2_vpc_subnet_facts:
        region: "{{ whc_region }}"
        filters:
          vpc-id: "{{ vpc_facts.vpcs[0].id }}"
      ignore_errors: 'yes'
      register: vpc_subnet_facts

    - name: Removing VPC Subnets
      ec2_vpc_subnet:
        region: "{{ whc_region }}"
        state: absent
        vpc_id: "{{ vpc_facts.vpcs[0].id }}"
        cidr: "{{ item.cidr_block }}" 
      ignore_errors: 'yes'
      with_items: "{{ vpc_subnet_facts.subnets }}"

    - name: Removing VPC
      ec2_vpc_net:
        region: "{{ whc_region }}"
        state: absent
        name: "{{ vpc_name }}" 
        cidr_block: "{{ whc_cidrblock }}"
      #ignore_errors: 'yes'
      when: vpc_facts is defined

    - name: Removing VPC Associated EC2 Key Pair
      ec2_key:
        name: "{{ key_name }}"
        state: absent
        region: "{{ whc_region }}"
      ignore_errors: 'yes'
      when: vpc_facts is defined  
