# vim:ff=unix ts=2 sw=2 ai expandtab

- hosts: localhost
  connection: local
  remote_user: ec2-user
  gather_facts: no

  vars_files:
    - "iam/roles/{{ awsaccount }}/roles.yaml"

  vars: []

  pre_tasks: 
    - name: Validate AWS Account value was passed
      fail: msg="ERROR --- A valid awsaccount value was not passed in extra-vars. Valid values are listed in group_vars/all"
      when: awsaccount is not defined or (awsaccount is defined and awsaccount not in awsaccounts)

    # Override default state value if passed
    - set_fact:
         state: "{{ rolestate }}"
      when: rolestate is defined

    - set_fact:
         state: 'present'
      when: rolestate is not defined

  #Make this apply all specific group
  roles:
  - name: Manage IAM Roles
    role: manage-iam-role
    managed_roles: "{{ iam_roles }}"
