---
# tasks file for security-group
- name: Create Security Groups
  ec2_group:
    name: "{{ item.key }}"
    description: "{{ item.value.sg_desc }}"
    vpc_id: "{{ whc_vpc.vpc.id }}"
    region: "{{ whc_region }}"
    purge_rules: "{{ item.value.sg_purgein }}"
    purge_rules_egress: "{{ item.value.sg_purgeout }}"
    purge_tags: "{{ item.value.sg_purgetags }}"
    rules: "{{ item.value.sg_rules.ingress }}"
    rules_egress: "{{ item.value.sg_rules.egress }}"
    #Ansible 2.4+ feature
    tags: "{{ item.value.tags }}"
  register: new_sg_id
  with_dict: "{{ whc_core_sgs }}"

#Deprecated in Ansible 2.4+ - tags applied on creation
#- name: Tag Security Groups
#  ec2_tag:
#    resource: "{{ item.group_id }}"
#    region: "{{ whc_region }}"
#    state: present
#   tags:
#     Name: "{{ item.invocation.module_args.name }}"
#     Environment: "{{ targetenv }}"
# with_items: "{{ new_sg_id.results }}"
