---
# tasks file for vpc
- name: Create AWS VPC
  ec2_vpc_net:
    state: "{{ state }}"
    region: "{{ vpc_region }}"
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidrblock }}"
    dns_support: true
    dns_hostnames: true
  register: vpc_out

- name: Export VPC ID
  set_fact: whc_vpc="{{ vpc_out }}"
